vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        product_image:
            uri_prefix: /images/K-Skate/products_site
            upload_destination: '%kernel.project_dir%/public/assets/images/products'
        avatar_image:
            uri_prefix: /images/K-Skate/avatar_site
            upload_destination: '%kernel.project_dir%/public/assets/images/avatars'
